"""initial schema

Revision ID: 3c5f24b4252b
Revises: 
Create Date: 2026-10-01 18:14:49.547987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5f24b4252b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_client')),
    sa.UniqueConstraint('client_id', name=op.f('uq_api_client_client_id'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    op.create_table('customer_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_group')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_group_code'))
    )
    op.create_table('number_sequence',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_number_sequence'))
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('code', name=op.f('uq_supplier_code')),
    sa.UniqueConstraint('public_id', name=op.f('uq_supplier_public_id'))
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=False)

    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email'))
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouse_code')),
    sa.UniqueConstraint('public_id', name=op.f('uq_warehouse_public_id'))
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_activity_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_at'), ['at'], unique=False)

    op.create_table('adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_adjustment_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_adjustment_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustment')),
    sa.UniqueConstraint('number', name=op.f('uq_adjustment_number'))
    )
    op.create_table('api_token',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_client.id'], name=op.f('fk_api_token_client_id_api_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_api_token'))
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_client_id'), ['client_id'], unique=False)

    op.create_table('auth_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_auth_session_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_session'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customer_group.id'], name=op.f('fk_customer_group_id_customer_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_code')),
    sa.UniqueConstraint('public_id', name=op.f('uq_customer_public_id'))
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_product_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('barcode', name=op.f('uq_product_barcode')),
    sa.UniqueConstraint('public_id', name=op.f('uq_product_public_id')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_sku'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('supplier_ref', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_purchase_order_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_purchase_order_supplier_id_supplier')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_purchase_order_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order')),
    sa.UniqueConstraint('number', name=op.f('uq_purchase_order_number'))
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_transfer_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfer_from_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfer_to_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer')),
    sa.UniqueConstraint('number', name=op.f('uq_transfer_number'))
    )
    op.create_table('adjustment_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=False),
    sa.Column('system_qty', sa.Integer(), nullable=True),
    sa.CheckConstraint('counted_qty >= 0', name=op.f('ck_adjustment_line_counted_not_negative')),
    sa.ForeignKeyConstraint(['adjustment_id'], ['adjustment.id'], name=op.f('fk_adjustment_line_adjustment_id_adjustment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_adjustment_line_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustment_line'))
    )
    op.create_table('goods_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_goods_receipt_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], name=op.f('fk_goods_receipt_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_goods_receipt_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt')),
    sa.UniqueConstraint('number', name=op.f('uq_goods_receipt_number'))
    )
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_order_id'), ['order_id'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('qty_billed', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_purchase_order_line_qty_positive')),
    sa.CheckConstraint('qty_billed <= qty_received', name=op.f('ck_purchase_order_line_bill_only_received')),
    sa.CheckConstraint('qty_received <= qty', name=op.f('ck_purchase_order_line_not_over_received')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_line_order_id_purchase_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_purchase_order_line_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line'))
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_order_id'), ['order_id'], unique=False)

    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_ref', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_sales_order_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_sales_order_customer_id_customer')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_sales_order_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order')),
    sa.UniqueConstraint('external_id', name=op.f('uq_sales_order_external_id')),
    sa.UniqueConstraint('number', name=op.f('uq_sales_order_number'))
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_status'), ['status'], unique=False)

    op.create_table('stock_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.CheckConstraint('on_hand >= 0', name=op.f('ck_stock_level_on_hand_not_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_level_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_level_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_level')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name=op.f('uq_stock_level_product_id'))
    )
    op.create_table('stock_move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_number', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_move_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_stock_move_user_id_user_account')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_move_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_move'))
    )
    with op.batch_alter_table('stock_move', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_move_moved_at'), ['moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_move_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_move_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('transfer_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_transfer_line_qty_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_transfer_line_product_id_product')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], name=op.f('fk_transfer_line_transfer_id_transfer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_line'))
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_delivery_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], name=op.f('fk_delivery_order_id_sales_order')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_delivery_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery')),
    sa.UniqueConstraint('number', name=op.f('uq_delivery_number'))
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_order_id'), ['order_id'], unique=False)

    op.create_table('goods_receipt_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['purchase_order_line.id'], name=op.f('fk_goods_receipt_line_order_line_id_purchase_order_line')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_goods_receipt_line_product_id_product')),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipt.id'], name=op.f('fk_goods_receipt_line_receipt_id_goods_receipt'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_line'))
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('partner_ref', sa.String(length=60), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'customer' AND customer_id IS NOT NULL) OR (kind = 'supplier' AND supplier_id IS NOT NULL)", name=op.f('ck_invoice_partner_matches_kind')),
    sa.CheckConstraint('amount_paid >= 0 AND amount_paid <= total', name=op.f('ck_invoice_paid_within_total')),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_invoice_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_invoice_customer_id_customer')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_invoice_purchase_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], name=op.f('fk_invoice_sales_order_id_sales_order')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_invoice_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice')),
    sa.UniqueConstraint('number', name=op.f('uq_invoice_number'))
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('qty_delivered', sa.Integer(), nullable=False),
    sa.Column('qty_invoiced', sa.Integer(), nullable=False),
    sa.CheckConstraint('discount_pct >= 0 AND discount_pct <= 100', name=op.f('ck_sales_order_line_discount_range')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_sales_order_line_qty_positive')),
    sa.CheckConstraint('qty_delivered <= qty', name=op.f('ck_sales_order_line_not_over_delivered')),
    sa.CheckConstraint('qty_invoiced <= qty_delivered', name=op.f('ck_sales_order_line_invoice_only_delivered')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], name=op.f('fk_sales_order_line_order_id_sales_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sales_order_line_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_line'))
    )
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_line_order_id'), ['order_id'], unique=False)

    op.create_table('delivery_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], name=op.f('fk_delivery_line_delivery_id_delivery'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['sales_order_line.id'], name=op.f('fk_delivery_line_order_line_id_sales_order_line')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_delivery_line_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_line'))
    )
    op.create_table('invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_line_invoice_id_invoice'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_invoice_line_product_id_product')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], name=op.f('fk_invoice_line_purchase_order_line_id_purchase_order_line')),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_line.id'], name=op.f('fk_invoice_line_sales_order_line_id_sales_order_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line'))
    )
    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_amount_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_payment_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_payment_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('number', name=op.f('uq_payment_number'))
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_invoice_id'))

    op.drop_table('payment')
    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_invoice_id'))

    op.drop_table('invoice_line')
    op.drop_table('delivery_line')
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_line_order_id'))

    op.drop_table('sales_order_line')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_kind'))
        batch_op.drop_index(batch_op.f('ix_invoice_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    op.drop_table('goods_receipt_line')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_order_id'))

    op.drop_table('delivery')
    op.drop_table('transfer_line')
    with op.batch_alter_table('stock_move', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_move_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_move_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_move_moved_at'))

    op.drop_table('stock_move')
    op.drop_table('stock_level')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_status'))
        batch_op.drop_index(batch_op.f('ix_sales_order_customer_id'))

    op.drop_table('sales_order')
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_order_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_order_id'))

    op.drop_table('goods_receipt')
    op.drop_table('adjustment_line')
    op.drop_table('transfer')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_status'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_name'))

    op.drop_table('customer')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))

    op.drop_table('auth_session')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_client_id'))

    op.drop_table('api_token')
    op.drop_table('adjustment')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_at'))

    op.drop_table('activity')
    op.drop_table('warehouse')
    op.drop_table('user_account')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_name'))

    op.drop_table('supplier')
    op.drop_table('setting')
    op.drop_table('number_sequence')
    op.drop_table('customer_group')
    op.drop_table('category')
    op.drop_table('api_client')
    # ### end Alembic commands ###
