"""pos returns promotions loyalty

Revision ID: f05b8b137811
Revises: b421eeacfe30
Create Date: 2026-10-03 17:46:47.116663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05b8b137811'
down_revision: Union[str, Sequence[str], None] = 'b421eeacfe30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('buy_qty', sa.Integer(), nullable=False),
    sa.Column('get_qty', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('min_spend', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('percent', 'price', 'buy_get', 'voucher')", name=op.f('ck_promotion_kind_known')),
    sa.CheckConstraint('ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on', name=op.f('ck_promotion_dates_in_order')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_promotion_value_not_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_promotion_category_id_category')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_promotion_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_promotion_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion')),
    sa.UniqueConstraint('code', name=op.f('uq_promotion_code')),
    sa.UniqueConstraint('public_id', name=op.f('uq_promotion_public_id'))
    )
    op.create_table('sales_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('refunds', sa.JSON(), nullable=False),
    sa.Column('points_reversed', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_sales_return_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], name=op.f('fk_sales_return_order_id_sales_order')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_sales_return_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_return')),
    sa.UniqueConstraint('external_id', name=op.f('uq_sales_return_external_id')),
    sa.UniqueConstraint('number', name=op.f('uq_sales_return_number'))
    )
    with op.batch_alter_table('sales_return', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_return_date'), ['return_date'], unique=False)

    op.create_table('sales_return_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_sales_return_line_qty_positive')),
    sa.ForeignKeyConstraint(['order_line_id'], ['sales_order_line.id'], name=op.f('fk_sales_return_line_order_line_id_sales_order_line')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sales_return_line_product_id_product')),
    sa.ForeignKeyConstraint(['return_id'], ['sales_return.id'], name=op.f('fk_sales_return_line_return_id_sales_return'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_return_line'))
    )
    with op.batch_alter_table('sales_return_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_line_return_id'), ['return_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_returned', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_check_constraint(op.f('ck_sales_order_line_return_only_delivered'), 'qty_returned <= qty_delivered')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_sales_order_line_return_only_delivered'), type_='check')
        batch_op.drop_column('qty_returned')

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('loyalty_points')

    with op.batch_alter_table('sales_return_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_line_return_id'))

    op.drop_table('sales_return_line')
    with op.batch_alter_table('sales_return', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_return_date'))
        batch_op.drop_index(batch_op.f('ix_sales_return_order_id'))

    op.drop_table('sales_return')
    op.drop_table('promotion')
    # ### end Alembic commands ###
